# Generated by Django 5.0.6 on 2024-06-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_book_user_alter_book_author_alter_book_genres_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name'], 'verbose_name': 'Genre - category', 'verbose_name_plural': 'Genres - categories'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
    ]
