# Generated by Django 5.0.6 on 2024-06-09 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0005_alter_customuser_email_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('administrator', 'Administrator'), ('visitoruser', 'Visitor user'), ('librarian', 'Librarian'), ('staff', 'Staff')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
